# Generated by Django 5.2.15 on 2026-06-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Effort",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "segment_id",
                        "athlete_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("elapsed_time", models.IntegerField(blank=True, null=True)),
                ("avg_speed", models.FloatField(blank=True, null=True)),
                ("avg_watts", models.FloatField(blank=True, null=True)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("effort_id", models.TextField(blank=True, null=True)),
                ("activity_id", models.TextField(blank=True, null=True)),
                ("start_date_local", models.TextField(blank=True, null=True)),
                ("first_seen", models.TextField(blank=True, null=True)),
                ("last_seen", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "efforts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Athlete",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("badge", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kv",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("value", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("activity_type", models.TextField(blank=True, null=True)),
                ("display_location", models.TextField(blank=True, null=True)),
                ("climb_category", models.IntegerField(blank=True, null=True)),
                ("is_verified", models.IntegerField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                ("avg_grade", models.FloatField(blank=True, null=True)),
                ("elev_low", models.FloatField(blank=True, null=True)),
                ("elev_high", models.FloatField(blank=True, null=True)),
                ("elev_gain", models.FloatField(blank=True, null=True)),
                ("gross_gain", models.FloatField(blank=True, null=True)),
                ("gross_loss", models.FloatField(blank=True, null=True)),
                ("terrain", models.TextField(blank=True, null=True)),
                ("total_athletes", models.IntegerField(blank=True, null=True)),
                ("total_efforts", models.IntegerField(blank=True, null=True)),
                ("star_count", models.IntegerField(blank=True, null=True)),
                ("start_lat", models.FloatField(blank=True, null=True)),
                ("start_lng", models.FloatField(blank=True, null=True)),
                ("end_lat", models.FloatField(blank=True, null=True)),
                ("end_lng", models.FloatField(blank=True, null=True)),
                ("map_image_url", models.TextField(blank=True, null=True)),
                ("streams_json", models.TextField(blank=True, null=True)),
                ("difficulty", models.FloatField(blank=True, null=True)),
                ("in_town", models.IntegerField(blank=True, null=True)),
                ("starts_in_town", models.IntegerField(blank=True, null=True)),
                ("ends_in_town", models.IntegerField(blank=True, null=True)),
                ("passes_through", models.IntegerField(blank=True, null=True)),
                ("parent_segment_id", models.IntegerField(blank=True, null=True)),
                ("excluded", models.IntegerField(default=0)),
                ("discipline", models.TextField(blank=True, null=True)),
                ("fetched_at", models.TextField(blank=True, null=True)),
                ("efforts_fetched_at", models.TextField(blank=True, null=True)),
                ("last_depth_pages", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EffortLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elapsed_time", models.IntegerField(blank=True, null=True)),
                ("avg_speed", models.FloatField(blank=True, null=True)),
                ("avg_watts", models.FloatField(blank=True, null=True)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("effort_id", models.TextField(blank=True, null=True)),
                ("activity_id", models.TextField(blank=True, null=True)),
                ("start_date_local", models.TextField(blank=True, null=True)),
                ("observed_at", models.TextField()),
                (
                    "athlete",
                    models.ForeignKey(
                        db_column="athlete_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="segments.athlete",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        db_column="segment_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["segment", "observed_at"], name="idx_effort_log_seg"
                    ),
                    models.Index(
                        fields=["segment", "athlete"], name="idx_effort_log_athlete"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("segment", "athlete", "effort_id"),
                        name="uniq_effortlog_seg_ath_effort",
                    )
                ],
            },
        ),
        # Create the `efforts` SQL view — read-only; backed by segments_effortlog.
        # The Effort model is unmanaged (managed=False) and produces no DDL here;
        # this RunSQL is the only place the view is created/dropped.
        # After the one-time manual SQL rename (segments → segments_segment, etc.)
        # the view references `segments_effortlog` — the Django default table name.
        migrations.RunSQL(
            sql="""
CREATE VIEW efforts AS
WITH best AS (
    SELECT segment_id, athlete_id, elapsed_time, avg_speed, avg_watts, avg_hr,
           effort_id, activity_id, start_date_local,
           ROW_NUMBER() OVER (
               PARTITION BY segment_id, athlete_id
               ORDER BY (elapsed_time IS NULL), elapsed_time ASC,
                        start_date_local ASC, id ASC) AS _rn
    FROM segments_effortlog
),
seen AS (
    SELECT segment_id, athlete_id,
           MIN(observed_at) AS first_seen,
           MAX(observed_at) AS last_seen
    FROM segments_effortlog GROUP BY segment_id, athlete_id
)
SELECT
    b.segment_id, b.athlete_id,
    CASE WHEN b.elapsed_time IS NULL THEN NULL ELSE RANK() OVER (
        PARTITION BY b.segment_id, (b.elapsed_time IS NULL)
        ORDER BY b.elapsed_time ASC) END AS rank,
    b.elapsed_time, b.avg_speed, b.avg_watts, b.avg_hr,
    b.effort_id, b.activity_id, b.start_date_local,
    s.first_seen, s.last_seen
FROM best b
JOIN seen s ON s.segment_id = b.segment_id AND s.athlete_id = b.athlete_id
WHERE b._rn = 1;
""",
            reverse_sql="DROP VIEW efforts;",
        ),
    ]
