# Generated by Django 5.2.15 on 2026-06-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0002_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="effortlog",
            name="gender",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="segment",
            name="climb_category",
            field=models.TextField(blank=True, null=True),
        ),
    ]
